# Generated by Django 6.0.2 on 2026-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenFabricacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of', models.CharField(max_length=20, unique=True, verbose_name='Número de OF')),
                ('referencia', models.CharField(blank=True, max_length=20, null=True, verbose_name='OF Referencia')),
                ('descripcion', models.TextField(verbose_name='Descripción del trabajo')),
                ('cliente', models.CharField(max_length=150)),
                ('tipo_grabado', models.CharField(max_length=50, verbose_name='Tipo de Grabado')),
                ('proceso', models.CharField(max_length=50)),
                ('maquina', models.CharField(max_length=100, verbose_name='Máquina')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Prog.')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('REVISION', 'En Revisión'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación Física')),
                ('sobre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Sobre/Caja')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden de Fabricación',
                'verbose_name_plural': 'Órdenes de Fabricación',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
