# Generated by Django 6.0.2 on 2026-05-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='cantidad_formatos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Formatos'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='horas_proceso',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas Proceso'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='papel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Papel'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='maquina',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='tipo_grabado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Grabado'),
        ),
    ]
