# Generated by Django 6.0.2 on 2026-06-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0002_ordenfabricacion_cantidad_formatos_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordenfabricacion',
            unique_together={('of', 'proceso')},
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='compensacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compensación'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='perdida',
            field=models.FloatField(blank=True, null=True, verbose_name='Pérdida'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='peso_final',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Final'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='peso_inicial',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Inicial'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='responsables',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsables'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='rpm',
            field=models.IntegerField(blank=True, null=True, verbose_name='RPM'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatura'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='tiempo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo'),
        ),
        migrations.RemoveField(
            model_name='ordenfabricacion',
            name='responsable',
        ),
    ]
