# Generated by Django 6.0.2 on 2026-06-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0003_alter_ordenfabricacion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='actualizado_el',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='cantidad_formatos',
            field=models.IntegerField(blank=True, help_text='Volumen total de formatos a producir.', null=True, verbose_name='Cantidad Formatos'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='cliente',
            field=models.CharField(help_text='Nombre del cliente propietario de la orden.', max_length=150, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='compensacion',
            field=models.CharField(blank=True, help_text='Ajustes técnicos de compensación realizados.', max_length=100, null=True, verbose_name='Compensación'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='descripcion',
            field=models.TextField(help_text='Detalle del producto o trabajo a realizar.', verbose_name='Descripción del trabajo'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('EN_MAQUINA', 'En Máquina'), ('COMPLETADO', 'Completado'), ('REVISION', 'En Revisión'), ('CANCELADO', 'Cancelado'), ('REPETIR', 'Para Repetir')], default='PENDIENTE', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha de producción establecida en la planificación.', null=True, verbose_name='Fecha Prog.'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='horas_proceso',
            field=models.FloatField(blank=True, help_text='Tiempo estimado de producción en horas.', null=True, verbose_name='Horas Proceso'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='maquina',
            field=models.CharField(blank=True, help_text='Máquina asignada para el proceso.', max_length=100, null=True, verbose_name='Máquina'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='of',
            field=models.CharField(help_text='Número identificador único de la orden de fabricación.', max_length=20, verbose_name='Número de OF'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='papel',
            field=models.CharField(blank=True, help_text='Tipo de papel a utilizar.', max_length=100, null=True, verbose_name='Papel'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='perdida',
            field=models.FloatField(blank=True, help_text='Diferencia de peso calculada durante el proceso.', null=True, verbose_name='Pérdida'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='peso_final',
            field=models.FloatField(blank=True, help_text='Peso del material al finalizar el proceso.', null=True, verbose_name='Peso Final'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='peso_inicial',
            field=models.FloatField(blank=True, help_text='Peso del material al iniciar el proceso.', null=True, verbose_name='Peso Inicial'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='proceso',
            field=models.CharField(help_text='Departamento: STAMPING o EMBOSSING.', max_length=50, verbose_name='Proceso'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='referencia',
            field=models.CharField(blank=True, help_text='Número de OF de referencia si aplica.', max_length=20, null=True, verbose_name='OF Referencia'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='responsables',
            field=models.CharField(blank=True, help_text='Nombres de los operarios que trabajaron en la orden.', max_length=255, null=True, verbose_name='Responsables'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='rpm',
            field=models.IntegerField(blank=True, help_text='Revoluciones por minuto de la maquinaria.', null=True, verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='sobre',
            field=models.CharField(blank=True, help_text='Identificador del sobre o caja de arte.', max_length=100, null=True, verbose_name='Número de Sobre/Caja'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='temp',
            field=models.FloatField(blank=True, help_text='Temperatura de trabajo en grados centígrados.', null=True, verbose_name='Temperatura'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='tiempo',
            field=models.CharField(blank=True, help_text='Duración real del proceso técnico.', max_length=50, null=True, verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='tipo_grabado',
            field=models.CharField(blank=True, help_text='Especificación del tipo de grabado solicitado.', max_length=50, null=True, verbose_name='Tipo de Grabado'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Lugar donde se encuentra el grabado físico (ej. Cajón A1).', max_length=200, null=True, verbose_name='Ubicación Física'),
        ),
    ]
