# Generated by Django 6.0.2 on 2026-06-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0004_alter_ordenfabricacion_actualizado_el_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='fecha_registro',
            field=models.DateField(blank=True, help_text='Fecha en la que el usuario guardó el registro en EIS.', null=True, verbose_name='Fecha de Guardado'),
        ),
    ]
