# Generated by Django 6.0.2 on 2026-06-16 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0005_ordenfabricacion_fecha_registro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario del sistema que realizó la última acción sobre este registro.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Registro'),
        ),
    ]
