# Generated by Django 6.0.2 on 2026-06-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0006_ordenfabricacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='foto_dano',
            field=models.ImageField(blank=True, help_text='Evidencia visual en caso de reporte de daño o repetición.', null=True, upload_to='grabados/danos/%Y/%m/', verbose_name='Foto de Daño'),
        ),
        migrations.AddField(
            model_name='ordenfabricacion',
            name='usos_acumulados',
            field=models.IntegerField(default=0, help_text='Contador de veces que este grabado ha pasado por producción.', verbose_name='Usos Acumulados'),
        ),
    ]
