# Generated by Django 6.0.2 on 2026-08-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0007_ordenfabricacion_foto_dano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='perdida',
            field=models.FloatField(blank=True, help_text='Diferencia de peso calculada durante el proceso, en gramos.', null=True, verbose_name='Pérdida (g)'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='peso_final',
            field=models.FloatField(blank=True, help_text='Peso del material al finalizar el proceso, en gramos.', null=True, verbose_name='Peso Final (g)'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='peso_inicial',
            field=models.FloatField(blank=True, help_text='Peso del material al iniciar el proceso, en kilogramos.', null=True, verbose_name='Peso Inicial (kg)'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='tiempo',
            field=models.CharField(blank=True, help_text='Duración real del proceso técnico, en minutos.', max_length=50, null=True, verbose_name='Tiempo Real (min)'),
        ),
    ]
