# Generated by Django 6.0.2 on 2026-08-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0008_alter_ordenfabricacion_perdida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='peso_inicial',
            field=models.FloatField(blank=True, help_text='Peso del material al iniciar el proceso, en gramos.', null=True, verbose_name='Peso Inicial (g)'),
        ),
    ]
