# Generated by Django 6.0.2 on 2026-08-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0009_alter_ordenfabricacion_peso_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='origen_manual',
            field=models.BooleanField(default=False, help_text='Se marca solo cuando el grabado se registró desde la pantalla temporal de Fabricación, en vez de venir de la programación de Plani.', verbose_name='Alta manual (Fabricación)'),
        ),
    ]
