# Generated by Django 6.0.2 on 2026-08-13 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0010_ordenfabricacion_origen_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_acumulados', models.FloatField(default=0, verbose_name='ML acumulados desde la última renovación')),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('ultima_renovacion', models.DateTimeField(blank=True, null=True)),
                ('renovado_por', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Estado del Baño',
                'verbose_name_plural': 'Estado del Baño',
            },
        ),
    ]
