# Generated by Django 6.0.2 on 2026-08-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0011_estadobano'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenfabricacion',
            name='compensacion_motivo',
            field=models.TextField(blank=True, help_text='Explicación de por qué se cambió la compensación respecto al valor recomendado (Pérdida × 6.6).', null=True, verbose_name='Motivo del ajuste de compensación'),
        ),
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='compensacion',
            field=models.CharField(blank=True, help_text='Cantidad de compensación de baño aplicada, en ml.', max_length=100, null=True, verbose_name='Compensación (ml)'),
        ),
    ]
