# Generated by Django 6.0.2 on 2026-08-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0012_ordenfabricacion_compensacion_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenfabricacion',
            name='origen_manual',
            field=models.BooleanField(default=False, help_text='Se marca solo cuando el grabado se registró desde la pantalla temporal de Fabricación, en vez de venir de la programación de Planning.', verbose_name='Alta manual (Fabricación)'),
        ),
    ]
