# Generated by Django 6.0.2 on 2026-10-06 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0013_alter_ordenfabricacion_origen_manual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of_origen', models.CharField(help_text='Solo dígitos, misma normalización que el PLANI.', max_length=20, verbose_name='OF de origen')),
                ('proceso', models.CharField(choices=[('STAMPING', 'Stamping'), ('EMBOSSING', 'Embossing')], max_length=20, verbose_name='Proceso')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('referencia', models.CharField(blank=True, help_text='Descripción del producto (G_Referencia).', max_length=255, verbose_name='Referencia')),
                ('sobre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobre/Caja')),
                ('datos_manuales', models.BooleanField(default=False, help_text='La OF de origen no se encontró en la API.', verbose_name='Datos cargados a mano')),
                ('estado', models.CharField(choices=[('EN_FABRICACION', 'En Fabricación'), ('PENDIENTE_K1', 'Pendiente de K1'), ('APROBADO', 'Aprobado'), ('EN_MAQUINA', 'En Máquina'), ('REPETIR', 'Para Repetir')], default='EN_FABRICACION', max_length=20, verbose_name='Estado')),
                ('aprobado_legado', models.BooleanField(default=False, help_text='Migrado desde OrdenFabricacion; nunca pasó K1 en EIS.', verbose_name='Aprobado sin K1 (legado)')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación física')),
                ('usos_acumulados', models.PositiveIntegerField(default=0, verbose_name='Usos acumulados')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado_el', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Grabado',
                'verbose_name_plural': 'Grabados',
                'ordering': ['-actualizado_el'],
            },
        ),
        migrations.CreateModel(
            name='FabricacionGrabado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='N° de fabricación')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Fabricación inicial'), ('RECHAZO_K1', 'Refabricación por K1 rechazado'), ('REPETICION', 'Refabricación por REPETIR')], max_length=20, verbose_name='Tipo')),
                ('responsables', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsables')),
                ('peso_inicial', models.FloatField(blank=True, null=True, verbose_name='Peso Inicial (g)')),
                ('peso_final', models.FloatField(blank=True, null=True, verbose_name='Peso Final (g)')),
                ('perdida', models.FloatField(blank=True, null=True, verbose_name='Pérdida (g)')),
                ('temp', models.FloatField(blank=True, null=True, verbose_name='Temperatura')),
                ('rpm', models.IntegerField(blank=True, null=True, verbose_name='RPM')),
                ('tiempo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tiempo Real (min)')),
                ('compensacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Compensación (ml)')),
                ('compensacion_motivo', models.TextField(blank=True, null=True, verbose_name='Motivo del ajuste de compensación')),
                ('bano_ml', models.FloatField(default=0, verbose_name='ML sumados al baño')),
                ('registrado_el', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('grabado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabricaciones', to='gestion_grabados.grabado')),
            ],
            options={
                'verbose_name': 'Fabricación de grabado',
                'verbose_name_plural': 'Fabricaciones de grabado',
                'ordering': ['grabado', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='EnvioMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('of', models.CharField(max_length=20, verbose_name='OF del PLANI')),
                ('fecha_programada', models.DateField(blank=True, null=True, verbose_name='Fecha Prog.')),
                ('cantidad_formatos', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Formatos')),
                ('horas_proceso', models.FloatField(blank=True, null=True, verbose_name='Horas Proceso')),
                ('papel', models.CharField(blank=True, max_length=100, null=True, verbose_name='Papel')),
                ('enviado_el', models.DateTimeField(verbose_name='Fecha de envío')),
                ('recogido_el', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de recogida')),
                ('estado_fisico', models.CharField(blank=True, choices=[('OK', 'OK'), ('REPETIR', 'Repetir')], max_length=10, null=True, verbose_name='Estado físico')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentario')),
                ('foto_dano', models.ImageField(blank=True, null=True, upload_to='grabados/danos/%Y/%m/', verbose_name='Foto de Daño')),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ubicación al recoger')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('recogido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Recogido por')),
                ('grabado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='gestion_grabados.grabado')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='gestion_grabados.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Envío a máquina',
                'verbose_name_plural': 'Envíos a máquina',
                'ordering': ['-enviado_el'],
            },
        ),
        migrations.CreateModel(
            name='LegadoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('FABRICACION', 'Convertida en FabricacionGrabado'), ('USO', 'Uso del grabado (solo histórico)'), ('ENVIO_ABIERTO', 'Convertida en EnvioMaquina abierto'), ('SIN_MIGRAR', 'Sin migrar (ej. PENDIENTE)')], max_length=20, verbose_name='Rol')),
                ('migrado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de migración')),
                ('envio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_legado', to='gestion_grabados.enviomaquina')),
                ('fabricacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_legado', to='gestion_grabados.fabricaciongrabado')),
                ('grabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_legado', to='gestion_grabados.grabado')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legado', to='gestion_grabados.ordenfabricacion')),
            ],
            options={
                'verbose_name': 'Enlace con orden legada',
                'verbose_name_plural': 'Enlaces con órdenes legadas',
            },
        ),
        migrations.CreateModel(
            name='PruebaK1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.PositiveIntegerField(verbose_name='Intento')),
                ('resultado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Resultado')),
                ('motivo_rechazo', models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo')),
                ('decidido_el', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de decisión')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Decidido por')),
                ('fabricacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='prueba_k1', to='gestion_grabados.fabricaciongrabado')),
                ('grabado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_k1', to='gestion_grabados.grabado')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_k1', to='gestion_grabados.maquina', verbose_name='Máquina')),
            ],
            options={
                'verbose_name': 'Prueba K1',
                'verbose_name_plural': 'Pruebas K1',
                'ordering': ['grabado', 'intento'],
                'permissions': [('decidir_pruebak1', 'Puede aprobar o rechazar pruebas K1')],
            },
        ),
        migrations.AddIndex(
            model_name='grabado',
            index=models.Index(fields=['estado'], name='grabado_estado_idx'),
        ),
        migrations.AddConstraint(
            model_name='grabado',
            constraint=models.UniqueConstraint(fields=('of_origen', 'proceso'), name='grabado_unico_of_proceso'),
        ),
        migrations.AddConstraint(
            model_name='fabricaciongrabado',
            constraint=models.UniqueConstraint(fields=('grabado', 'numero'), name='fabricacion_numero_unico'),
        ),
        migrations.AddIndex(
            model_name='enviomaquina',
            index=models.Index(fields=['of'], name='envio_of_idx'),
        ),
        migrations.AddConstraint(
            model_name='enviomaquina',
            constraint=models.UniqueConstraint(condition=models.Q(('recogido_el__isnull', True)), fields=('grabado',), name='envio_uno_abierto_por_grabado'),
        ),
        migrations.AddConstraint(
            model_name='pruebak1',
            constraint=models.UniqueConstraint(fields=('grabado', 'intento'), name='k1_intento_unico'),
        ),
        migrations.AddConstraint(
            model_name='pruebak1',
            constraint=models.UniqueConstraint(condition=models.Q(('resultado', 'PENDIENTE')), fields=('grabado',), name='k1_un_pendiente_por_grabado'),
        ),
        migrations.AddConstraint(
            model_name='pruebak1',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resultado', 'RECHAZADO'), _negated=True), ('motivo_rechazo__isnull', False), _connector='OR'), name='k1_rechazo_con_motivo'),
        ),
    ]
