# Generated by Django 6.0.2 on 2026-10-06 03:54

from django.contrib.auth.management import create_permissions
from django.db import migrations

GRUPO_SUPERVISORES = 'Supervisores de Producción'
CODENAME_DECIDIR_K1 = 'decidir_pruebak1'


def crear_grupo_supervisores(apps, schema_editor):
    """Crea el grupo "Supervisores de Producción" con el permiso para aprobar o
    rechazar pruebas K1. Los usuarios se agregan al grupo a mano desde /crdadmin/."""
    db_alias = schema_editor.connection.alias

    # Los permisos de Meta.permissions se crean recién en la señal post_migrate,
    # que corre al final de `migrate`; acá se fuerzan para poder asignarlos ya.
    app_config = apps.get_app_config('gestion_grabados')
    app_config.models_module = True
    create_permissions(app_config, apps=apps, verbosity=0, using=db_alias)
    app_config.models_module = None

    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    permiso = Permission.objects.using(db_alias).get(
        codename=CODENAME_DECIDIR_K1,
        content_type__app_label='gestion_grabados',
        content_type__model='pruebak1',
    )
    grupo, _ = Group.objects.using(db_alias).get_or_create(name=GRUPO_SUPERVISORES)
    grupo.permissions.add(permiso)


def quitar_grupo_supervisores(apps, schema_editor):
    """Reversa: saca el permiso del grupo y borra el grupo solo si quedó sin
    permisos (por si alguien le asignó otros a mano)."""
    db_alias = schema_editor.connection.alias
    Group = apps.get_model('auth', 'Group')

    grupo = Group.objects.using(db_alias).filter(name=GRUPO_SUPERVISORES).first()
    if grupo is None:
        return
    grupo.permissions.remove(*grupo.permissions.filter(
        codename=CODENAME_DECIDIR_K1,
        content_type__app_label='gestion_grabados',
    ))
    if not grupo.permissions.exists():
        grupo.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('gestion_grabados', '0014_maquina_grabado_fabricaciongrabado_enviomaquina_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_grupo_supervisores, quitar_grupo_supervisores),
    ]
