# Generated by Django 6.0.2 on 2026-10-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_grabados', '0015_grupo_supervisores_produccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enviomaquina',
            name='foto_dano',
        ),
    ]
